In [1]:
import numpy as np
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
import numpy as np
arr=np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [3]:
import numpy as np
arr=np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [4]:
import numpy as np
arr=np.arange(2,21,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [6]:
import numpy as np
arr=np.array([[1,2,3],[2,3,4]])
print(arr.shape)

(2, 3)


In [7]:
import numpy as np
arr=np.array([[2,3,4],[2,8,9]])
print(arr.size)

6


In [8]:
import numpy as np
arr=np.array([2,3,4,5])
print(arr[0])
print(arr[-1])
print(arr[2])

2
5
4


In [9]:
import numpy as np
arr=np.array([1,2,3,4])
arr[2]=9
print(arr)

[1 2 9 4]


In [10]:
import numpy as np
arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
import numpy as np
arr=np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
import numpy as np
arr=np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
import numpy as np
arr=np.random.randint(1,101,10)
print(arr)


[54 41 48 14 37  7 95 33 17 51]


In [16]:
import numpy as np
arr=np.array([1,2,4,5,6])
print(arr.max())
print(arr.min())

6
1


In [17]:
import numpy as np
arr=np.array([2,3,4,6])
print(arr.sum())

15


In [18]:
import numpy as np
arr=np.array([2,3,5,6,7,9])
print(arr.mean())

5.333333333333333


In [19]:
import numpy as np
arr=np.array([1,2,4,3,7,9])
print(np.sort(arr))

[1 2 3 4 7 9]


In [20]:
import numpy as np
arr=np.array([1,2,4,5,6])
print(arr[::-1])

[6 5 4 2 1]


In [21]:
import numpy as np
arr=np.array([69,5,6,90,4,5,57])
a=arr[arr>50]
print(a)

[69 90 57]


In [23]:
import numpy as np
arr=np.array([20,23,90,20,56])
count=np.count_nonzero(arr==20)
print(count)

2


In [27]:
import numpy as np
arr=np.arange(1,13)
a=arr.reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
import numpy as np
arr=np.array([[1,2,3],[2,3,4]])
print(arr.flatten())

[1 2 3 2 3 4]


In [30]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


In [31]:
import numpy as np
a=np.array([1,2,4,5])
b=np.array([2,3,5,6])
print(a-b)

[-1 -1 -1 -1]


In [32]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([1,2,4,5])
print(a*b)

[ 1  4 12 20]


In [33]:
import numpy as np
a=np.array([12,3,4,5])
b=np.array([2,5,6,7])
print(a/b)

[6.         0.6        0.66666667 0.71428571]


In [34]:
import numpy as np
arr=np.array([[1,2,3],[2,3,4]])
a=np.sum(arr,axis=1)
print(a)

[6 9]


In [36]:
import numpy as np
arr=np.array([[1,3,4,5],[3,4,5,8]])
b=np.sum(arr,axis=0)
print(b)

[ 4  7  9 13]


In [39]:
import numpy as np
arr=np.array([[2,3,4],[9,5,6]])
print(arr[0])

[2 3 4]


In [40]:
import numpy as np
arr=np.array([[1,2,9],[2,3,5]])
print(arr[:, -1])

[9 5]


In [41]:
import numpy as np
arr=np.array([-9,-8,-7,3,3,4,5])
arr[arr<0]=0
print(arr)

[0 0 0 3 3 4 5]
