In [4]:
import numpy as np

In [5]:
#1. Create a NumPy array containing numbers from 1 to 10.
a=np.arange(1,11)#starts at 1 and stops before 11, producing the integers 1 through 10.
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
#2. Create an array of 5 zeros.
a=np.zeros(5)#without any datatype declaration it stores float value
print(a)

[0. 0. 0. 0. 0.]


In [7]:
#3. Create an array of 5 ones.
a=np.ones(5,dtype=int)
print(a)

[1 1 1 1 1]


In [8]:
#4. Create an array containing only even numbers from 2 to 20.
a=np.arange(2,21,2)#2 is step size
print(a)

[ 2  4  6  8 10 12 14 16 18 20]


In [9]:
#5.shape of the matrix
a= np.array([[2,3], [4,6]])
print(a.shape)

(2, 2)


In [10]:
#6.size of an array
a=np.array([1,2,3,4,5])
print(a.size)

5


In [11]:
#7.find 1st,3rd, and last value in the array
arr=np.array([1,2,3,4,5])
print(arr[0])# First
print(arr[-1])# Last
print(arr[2])# Third

1
5
3


In [12]:
#8.replace the index of 3 or a[2]
a=np.array([1,2,3,4,5])
a[2]=100
print(a)

[  1   2 100   4   5]


In [13]:
#9.create 3*3 matrix with zeros
a=np.zeros((3,3))
print(a)
#10.create 4*4 matrix with ones
b=np.ones((4, 4))
print(b)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
#11.create an identity 5*5 matrix
a=np.eye(5,dtype=int)
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [15]:
#12. find 10 random between 1 to 100
a=np.random.randint(1,101,10)
print(a)

[74 36 44 70 22 61 94 81 37 51]


In [16]:
#13. min and max of an arr
arr=np.array([10,25,5,80,45])
print(arr.max())
print(arr.min())

80
5


In [17]:
#14.sum of array
z=np.array([1,2,3,4,5])
print(z.sum())
#15.mean of array
q=np.array([10,20,40,50])
print(q.mean())

15
30.0


In [18]:
#16.sorting of array
ar=np.array([5,2,8,1,9])
print(np.sort(ar))
#17.reverse
arr=np.array([1,2,3,4,5])
print(arr[::-1])

[1 2 5 8 9]
[5 4 3 2 1]


In [19]:
#18.add values greater than 50 in array
c=np.array([10,60,30,80,45,90])
print(c[c>50])

[60 80 90]


In [20]:
#19.cout the value of nonzero in arr
arr=np.array([1,2,2,3,2,4])
print(np.count_nonzero(arr==2))

3


In [21]:
#20.reshape the arr
arr=np.arange(1,13)
print(arr.reshape(3,4))
#21.flatten the arr
arr=np.array([[1,2],[3,4]])
print(arr.flatten())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]


In [22]:
#22.add 2 matrix
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
#23.subtract 2 matrix
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a-b)
#24.multiply 2 matrix
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a*b)
#25.divide 2 matrix
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [23]:
#26.row-wise sum of a matrix
a=np.array([[1,2,3],[4,5,6]])
print(a.sum(axis=1))
#27.column-wise sum of a matrix
a=np.array([[1,2,3],[4,5,6]])
print(a.sum(axis=0))

[ 6 15]
[5 7 9]


In [24]:
#28.Extract the first row from a matrix
arr = np.array([[1,2,3],[4,5,6]])
print(arr[0])
#29.Extract the last row from a matrix
arr = np.array([[1,2,3],[4,5,6]])
print(arr[-1])

[1 2 3]
[4 5 6]


In [25]:
#30.replace negtive with zero
a=np.array([-5,10,-2,-8,-1])
a[a<0]=0
print(a)

[ 0 10  0  0  0]
